### PR TITLE
FS signals and Nim release notes

### PR DESCRIPTION
**Pull request by ehmry**

### CODE REVIEW

**Comment by ehmry** [comment]
Please correct me on the Nim section if I am putting my own words into anyone's mouth.

**Comment by nfeske** [comment]
Thanks for your fantastic contributions. I like the motivation parts a lot.

Would you find it worthwhile to add a few words about exploring Nim on Genode? E.g., providing a hint how to get started, like installing the tool chain, and possibly referring to a code example?

Btw, your addition of Nim support motivated me to take a closer look at Nim at my leisure time. It is a very inviting yet sophisticated language - I really like it!

**Comment by ehmry** [comment]
Good, I'm glad you like it, I'm not sure it can achieve the same low-complexity of the base C++ code but for high-level stuff it I think it enforces a very reasonable amount of discipline.

I've update the documentation to cover what was done to the compiler, but I left out a code example, I wasn't sure what would be appropriate.

**Comment by ehmry** [comment]
I have some minor fixups at f7cca94e4aa1f524554c3fdda5eee292c9ef1c15

**Pull request closed without merging**
